### ISSUE TITLE
gyyu 2주차 목표

### ISSUE THREAD

**Issue by yurudehd** [42StudyGame/RandomDiceDefense42-Client#2]
## 이번주 목표
- [x] 인터페이스 만들기
- [x] 버튼 누르면 다이스 생성 (2H 30M)
- 1. [x] 다이스 구현 (1H) 
- 1. [x] 버튼 구현 (30M)
- 2. [x] 랜덤 위치에 다이스 생성 (1H)
- [x] 라인 따라 적 이동 (3H)
- 1. [x] 적 구현 (1H)
- 1. [x] 적이 이동하는 라인 구현 (1H)
- 2. [x] 시작지점에 적 생성, 라인따라 이동, 끝지점에서 소멸 (1H)

**Comment by yurudehd** [comment]
이번주는 miniRT때문에 바쁠거 같아서 작게 잡았습니다..더 하게 되면 추가로 업데이트 하겠습니다.

**Comment by jongfeel** [comment]
큰 작업은 잘 잡으신 것 같고 더 자세한 작업으로 나눠서 하시면 좋을 것 같습니다.

그리고 어려울 수 있지만 계획한 시간과 실제 투입한 시간을 기록 하시면 좋겠습니다.

**Comment by yurudehd** [comment]
수정해서 다시 올렸습니다.
